{
  "__allowedLegacyNames": [],
  "_queryType": "Query",
  "_mutationType": "Mutation",
  "_subscriptionType": null,
  "_directives": [
    "@include",
    "@skip",
    "@deprecated"
  ],
  "_typeMap": {
    "Query": "Query",
    "String": "String",
    "CodeOfConduct": "CodeOfConduct",
    "Node": "Node",
    "ID": "ID",
    "URI": "URI",
    "License": "License",
    "LicenseRule": "LicenseRule",
    "Boolean": "Boolean",
    "MarketplaceCategory": "MarketplaceCategory",
    "Int": "Int",
    "MarketplaceListing": "MarketplaceListing",
    "App": "App",
    "DateTime": "DateTime",
    "HTML": "HTML",
    "MarketplaceListingConnection": "MarketplaceListingConnection",
    "MarketplaceListingEdge": "MarketplaceListingEdge",
    "PageInfo": "PageInfo",
    "GitHubMetadata": "GitHubMetadata",
    "GitObjectID": "GitObjectID",
    "Organization": "Organization",
    "Actor": "Actor",
    "RegistryPackageOwner": "RegistryPackageOwner",
    "RegistryPackageSearch": "RegistryPackageSearch",
    "ProjectOwner": "ProjectOwner",
    "Project": "Project",
    "Closable": "Closable",
    "Updatable": "Updatable",
    "ProjectColumnConnection": "ProjectColumnConnection",
    "ProjectColumnEdge": "ProjectColumnEdge",
    "ProjectColumn": "ProjectColumn",
    "ProjectCardArchivedState": "ProjectCardArchivedState",
    "ProjectCardConnection": "ProjectCardConnection",
    "ProjectCardEdge": "ProjectCardEdge",
    "ProjectCard": "ProjectCard",
    "ProjectCardItem": "ProjectCardItem",
    "Issue": "Issue",
    "Assignable": "Assignable",
    "UserConnection": "UserConnection",
    "UserEdge": "UserEdge",
    "User": "User",
    "RepositoryOwner": "RepositoryOwner",
    "RepositoryPrivacy": "RepositoryPrivacy",
    "RepositoryOrder": "RepositoryOrder",
    "RepositoryOrderField": "RepositoryOrderField",
    "OrderDirection": "OrderDirection",
    "RepositoryAffiliation": "RepositoryAffiliation",
    "RepositoryConnection": "RepositoryConnection",
    "RepositoryEdge": "RepositoryEdge",
    "Repository": "Repository",
    "Subscribable": "Subscribable",
    "SubscriptionState": "SubscriptionState",
    "Starrable": "Starrable",
    "StarOrder": "StarOrder",
    "StarOrderField": "StarOrderField",
    "StargazerConnection": "StargazerConnection",
    "StargazerEdge": "StargazerEdge",
    "UniformResourceLocatable": "UniformResourceLocatable",
    "RepositoryInfo": "RepositoryInfo",
    "RepositoryLockReason": "RepositoryLockReason",
    "BranchProtectionRuleConnection": "BranchProtectionRuleConnection",
    "BranchProtectionRuleEdge": "BranchProtectionRuleEdge",
    "BranchProtectionRule": "BranchProtectionRule",
    "BranchProtectionRuleConflictConnection": "BranchProtectionRuleConflictConnection",
    "BranchProtectionRuleConflictEdge": "BranchProtectionRuleConflictEdge",
    "BranchProtectionRuleConflict": "BranchProtectionRuleConflict",
    "Ref": "Ref",
    "PullRequestState": "PullRequestState",
    "IssueOrder": "IssueOrder",
    "IssueOrderField": "IssueOrderField",
    "PullRequestConnection": "PullRequestConnection",
    "PullRequestEdge": "PullRequestEdge",
    "PullRequest": "PullRequest",
    "Comment": "Comment",
    "CommentAuthorAssociation": "CommentAuthorAssociation",
    "UserContentEditConnection": "UserContentEditConnection",
    "UserContentEditEdge": "UserContentEditEdge",
    "UserContentEdit": "UserContentEdit",
    "UpdatableComment": "UpdatableComment",
    "CommentCannotUpdateReason": "CommentCannotUpdateReason",
    "Labelable": "Labelable",
    "LabelConnection": "LabelConnection",
    "LabelEdge": "LabelEdge",
    "Label": "Label",
    "IssueState": "IssueState",
    "IssueConnection": "IssueConnection",
    "IssueEdge": "IssueEdge",
    "Lockable": "Lockable",
    "LockReason": "LockReason",
    "Reactable": "Reactable",
    "ReactionGroup": "ReactionGroup",
    "ReactionContent": "ReactionContent",
    "ReactingUserConnection": "ReactingUserConnection",
    "ReactingUserEdge": "ReactingUserEdge",
    "ReactionOrder": "ReactionOrder",
    "ReactionOrderField": "ReactionOrderField",
    "ReactionConnection": "ReactionConnection",
    "ReactionEdge": "ReactionEdge",
    "Reaction": "Reaction",
    "RepositoryNode": "RepositoryNode",
    "IssueCommentConnection": "IssueCommentConnection",
    "IssueCommentEdge": "IssueCommentEdge",
    "IssueComment": "IssueComment",
    "Deletable": "Deletable",
    "PullRequestCommitConnection": "PullRequestCommitConnection",
    "PullRequestCommitEdge": "PullRequestCommitEdge",
    "PullRequestCommit": "PullRequestCommit",
    "Commit": "Commit",
    "GitObject": "GitObject",
    "GitActor": "GitActor",
    "GitTimestamp": "GitTimestamp",
    "Blame": "Blame",
    "BlameRange": "BlameRange",
    "CommitCommentConnection": "CommitCommentConnection",
    "CommitCommentEdge": "CommitCommentEdge",
    "CommitComment": "CommitComment",
    "DeploymentOrder": "DeploymentOrder",
    "DeploymentOrderField": "DeploymentOrderField",
    "DeploymentConnection": "DeploymentConnection",
    "DeploymentEdge": "DeploymentEdge",
    "Deployment": "Deployment",
    "DeploymentStatus": "DeploymentStatus",
    "DeploymentStatusState": "DeploymentStatusState",
    "DeploymentState": "DeploymentState",
    "DeploymentStatusConnection": "DeploymentStatusConnection",
    "DeploymentStatusEdge": "DeploymentStatusEdge",
    "CommitAuthor": "CommitAuthor",
    "CommitHistoryConnection": "CommitHistoryConnection",
    "CommitEdge": "CommitEdge",
    "CommitConnection": "CommitConnection",
    "GitSignature": "GitSignature",
    "GitSignatureState": "GitSignatureState",
    "Status": "Status",
    "StatusContext": "StatusContext",
    "StatusState": "StatusState",
    "Tree": "Tree",
    "TreeEntry": "TreeEntry",
    "PullRequestChangedFileConnection": "PullRequestChangedFileConnection",
    "PullRequestChangedFileEdge": "PullRequestChangedFileEdge",
    "PullRequestChangedFile": "PullRequestChangedFile",
    "MergeableState": "MergeableState",
    "Milestone": "Milestone",
    "MilestoneState": "MilestoneState",
    "ReviewRequestConnection": "ReviewRequestConnection",
    "ReviewRequestEdge": "ReviewRequestEdge",
    "ReviewRequest": "ReviewRequest",
    "RequestedReviewer": "RequestedReviewer",
    "Team": "Team",
    "MemberStatusable": "MemberStatusable",
    "UserStatusOrder": "UserStatusOrder",
    "UserStatusOrderField": "UserStatusOrderField",
    "UserStatusConnection": "UserStatusConnection",
    "UserStatusEdge": "UserStatusEdge",
    "UserStatus": "UserStatus",
    "TeamConnection": "TeamConnection",
    "TeamEdge": "TeamEdge",
    "TeamOrder": "TeamOrder",
    "TeamOrderField": "TeamOrderField",
    "OrganizationInvitationConnection": "OrganizationInvitationConnection",
    "OrganizationInvitationEdge": "OrganizationInvitationEdge",
    "OrganizationInvitation": "OrganizationInvitation",
    "OrganizationInvitationType": "OrganizationInvitationType",
    "OrganizationInvitationRole": "OrganizationInvitationRole",
    "TeamMembershipType": "TeamMembershipType",
    "TeamMemberRole": "TeamMemberRole",
    "TeamMemberOrder": "TeamMemberOrder",
    "TeamMemberOrderField": "TeamMemberOrderField",
    "TeamMemberConnection": "TeamMemberConnection",
    "TeamMemberEdge": "TeamMemberEdge",
    "TeamPrivacy": "TeamPrivacy",
    "TeamRepositoryOrder": "TeamRepositoryOrder",
    "TeamRepositoryOrderField": "TeamRepositoryOrderField",
    "TeamRepositoryConnection": "TeamRepositoryConnection",
    "TeamRepositoryEdge": "TeamRepositoryEdge",
    "RepositoryPermission": "RepositoryPermission",
    "PullRequestReviewThreadConnection": "PullRequestReviewThreadConnection",
    "PullRequestReviewThreadEdge": "PullRequestReviewThreadEdge",
    "PullRequestReviewThread": "PullRequestReviewThread",
    "PullRequestReviewCommentConnection": "PullRequestReviewCommentConnection",
    "PullRequestReviewCommentEdge": "PullRequestReviewCommentEdge",
    "PullRequestReviewComment": "PullRequestReviewComment",
    "PullRequestReview": "PullRequestReview",
    "PullRequestReviewState": "PullRequestReviewState",
    "PullRequestReviewCommentState": "PullRequestReviewCommentState",
    "PullRequestReviewConnection": "PullRequestReviewConnection",
    "PullRequestReviewEdge": "PullRequestReviewEdge",
    "SuggestedReviewer": "SuggestedReviewer",
    "PullRequestTimelineConnection": "PullRequestTimelineConnection",
    "PullRequestTimelineItemEdge": "PullRequestTimelineItemEdge",
    "PullRequestTimelineItem": "PullRequestTimelineItem",
    "CommitCommentThread": "CommitCommentThread",
    "ClosedEvent": "ClosedEvent",
    "Closer": "Closer",
    "ReopenedEvent": "ReopenedEvent",
    "SubscribedEvent": "SubscribedEvent",
    "UnsubscribedEvent": "UnsubscribedEvent",
    "MergedEvent": "MergedEvent",
    "ReferencedEvent": "ReferencedEvent",
    "ReferencedSubject": "ReferencedSubject",
    "CrossReferencedEvent": "CrossReferencedEvent",
    "AssignedEvent": "AssignedEvent",
    "UnassignedEvent": "UnassignedEvent",
    "LabeledEvent": "LabeledEvent",
    "UnlabeledEvent": "UnlabeledEvent",
    "MilestonedEvent": "MilestonedEvent",
    "MilestoneItem": "MilestoneItem",
    "DemilestonedEvent": "DemilestonedEvent",
    "RenamedTitleEvent": "RenamedTitleEvent",
    "RenamedTitleSubject": "RenamedTitleSubject",
    "LockedEvent": "LockedEvent",
    "UnlockedEvent": "UnlockedEvent",
    "DeployedEvent": "DeployedEvent",
    "DeploymentEnvironmentChangedEvent": "DeploymentEnvironmentChangedEvent",
    "HeadRefDeletedEvent": "HeadRefDeletedEvent",
    "HeadRefRestoredEvent": "HeadRefRestoredEvent",
    "HeadRefForcePushedEvent": "HeadRefForcePushedEvent",
    "BaseRefForcePushedEvent": "BaseRefForcePushedEvent",
    "ReviewRequestedEvent": "ReviewRequestedEvent",
    "ReviewRequestRemovedEvent": "ReviewRequestRemovedEvent",
    "ReviewDismissedEvent": "ReviewDismissedEvent",
    "RefConnection": "RefConnection",
    "RefEdge": "RefEdge",
    "PushAllowanceConnection": "PushAllowanceConnection",
    "PushAllowanceEdge": "PushAllowanceEdge",
    "PushAllowance": "PushAllowance",
    "PushAllowanceActor": "PushAllowanceActor",
    "ReviewDismissalAllowanceConnection": "ReviewDismissalAllowanceConnection",
    "ReviewDismissalAllowanceEdge": "ReviewDismissalAllowanceEdge",
    "ReviewDismissalAllowance": "ReviewDismissalAllowance",
    "ReviewDismissalAllowanceActor": "ReviewDismissalAllowanceActor",
    "CollaboratorAffiliation": "CollaboratorAffiliation",
    "RepositoryCollaboratorConnection": "RepositoryCollaboratorConnection",
    "RepositoryCollaboratorEdge": "RepositoryCollaboratorEdge",
    "DeployKeyConnection": "DeployKeyConnection",
    "DeployKeyEdge": "DeployKeyEdge",
    "DeployKey": "DeployKey",
    "IssueOrPullRequest": "IssueOrPullRequest",
    "LanguageOrder": "LanguageOrder",
    "LanguageOrderField": "LanguageOrderField",
    "LanguageConnection": "LanguageConnection",
    "LanguageEdge": "LanguageEdge",
    "Language": "Language",
    "MilestoneOrder": "MilestoneOrder",
    "MilestoneOrderField": "MilestoneOrderField",
    "MilestoneConnection": "MilestoneConnection",
    "MilestoneEdge": "MilestoneEdge",
    "ProjectOrder": "ProjectOrder",
    "ProjectOrderField": "ProjectOrderField",
    "ProjectState": "ProjectState",
    "ProjectConnection": "ProjectConnection",
    "ProjectEdge": "ProjectEdge",
    "ProtectedBranchConnection": "ProtectedBranchConnection",
    "ProtectedBranchEdge": "ProtectedBranchEdge",
    "ProtectedBranch": "ProtectedBranch",
    "RefOrder": "RefOrder",
    "RefOrderField": "RefOrderField",
    "Release": "Release",
    "ReleaseAssetConnection": "ReleaseAssetConnection",
    "ReleaseAssetEdge": "ReleaseAssetEdge",
    "ReleaseAsset": "ReleaseAsset",
    "ReleaseOrder": "ReleaseOrder",
    "ReleaseOrderField": "ReleaseOrderField",
    "ReleaseConnection": "ReleaseConnection",
    "ReleaseEdge": "ReleaseEdge",
    "RepositoryTopicConnection": "RepositoryTopicConnection",
    "RepositoryTopicEdge": "RepositoryTopicEdge",
    "RepositoryTopic": "RepositoryTopic",
    "Topic": "Topic",
    "GitSSHRemote": "GitSSHRemote",
    "ContributionsCollection": "ContributionsCollection",
    "CommitContributionsByRepository": "CommitContributionsByRepository",
    "CommitContributionOrder": "CommitContributionOrder",
    "CommitContributionOrderField": "CommitContributionOrderField",
    "CreatedCommitContributionConnection": "CreatedCommitContributionConnection",
    "CreatedCommitContributionEdge": "CreatedCommitContributionEdge",
    "CreatedCommitContribution": "CreatedCommitContribution",
    "Contribution": "Contribution",
    "ContributionCalendar": "ContributionCalendar",
    "ContributionCalendarMonth": "ContributionCalendarMonth",
    "Date": "Date",
    "ContributionCalendarWeek": "ContributionCalendarWeek",
    "ContributionCalendarDay": "ContributionCalendarDay",
    "CreatedIssueOrRestrictedContribution": "CreatedIssueOrRestrictedContribution",
    "CreatedIssueContribution": "CreatedIssueContribution",
    "RestrictedContribution": "RestrictedContribution",
    "CreatedPullRequestOrRestrictedContribution": "CreatedPullRequestOrRestrictedContribution",
    "CreatedPullRequestContribution": "CreatedPullRequestContribution",
    "CreatedRepositoryOrRestrictedContribution": "CreatedRepositoryOrRestrictedContribution",
    "CreatedRepositoryContribution": "CreatedRepositoryContribution",
    "CreatedIssueContributionConnection": "CreatedIssueContributionConnection",
    "CreatedIssueContributionEdge": "CreatedIssueContributionEdge",
    "JoinedGitHubContribution": "JoinedGitHubContribution",
    "ContributionOrder": "ContributionOrder",
    "ContributionOrderField": "ContributionOrderField",
    "CreatedPullRequestContributionConnection": "CreatedPullRequestContributionConnection",
    "CreatedPullRequestContributionEdge": "CreatedPullRequestContributionEdge",
    "FollowerConnection": "FollowerConnection",
    "FollowingConnection": "FollowingConnection",
    "Gist": "Gist",
    "GistCommentConnection": "GistCommentConnection",
    "GistCommentEdge": "GistCommentEdge",
    "GistComment": "GistComment",
    "GistFile": "GistFile",
    "GistPrivacy": "GistPrivacy",
    "GistOrder": "GistOrder",
    "GistOrderField": "GistOrderField",
    "GistConnection": "GistConnection",
    "GistEdge": "GistEdge",
    "OrganizationConnection": "OrganizationConnection",
    "OrganizationEdge": "OrganizationEdge",
    "PublicKeyConnection": "PublicKeyConnection",
    "PublicKeyEdge": "PublicKeyEdge",
    "PublicKey": "PublicKey",
    "RepositoryContributionType": "RepositoryContributionType",
    "StarredRepositoryConnection": "StarredRepositoryConnection",
    "StarredRepositoryEdge": "StarredRepositoryEdge",
    "IssueTimelineConnection": "IssueTimelineConnection",
    "IssueTimelineItemEdge": "IssueTimelineItemEdge",
    "IssueTimelineItem": "IssueTimelineItem",
    "TransferredEvent": "TransferredEvent",
    "ProjectCardState": "ProjectCardState",
    "ProjectColumnPurpose": "ProjectColumnPurpose",
    "OrganizationMemberConnection": "OrganizationMemberConnection",
    "OrganizationMemberEdge": "OrganizationMemberEdge",
    "OrganizationMemberRole": "OrganizationMemberRole",
    "OrganizationIdentityProvider": "OrganizationIdentityProvider",
    "ExternalIdentityConnection": "ExternalIdentityConnection",
    "ExternalIdentityEdge": "ExternalIdentityEdge",
    "ExternalIdentity": "ExternalIdentity",
    "ExternalIdentitySamlAttributes": "ExternalIdentitySamlAttributes",
    "ExternalIdentityScimAttributes": "ExternalIdentityScimAttributes",
    "X509Certificate": "X509Certificate",
    "TeamRole": "TeamRole",
    "RateLimit": "RateLimit",
    "SearchType": "SearchType",
    "SearchResultItemConnection": "SearchResultItemConnection",
    "SearchResultItemEdge": "SearchResultItemEdge",
    "SearchResultItem": "SearchResultItem",
    "TextMatch": "TextMatch",
    "TextMatchHighlight": "TextMatchHighlight",
    "SecurityAdvisoryOrder": "SecurityAdvisoryOrder",
    "SecurityAdvisoryOrderField": "SecurityAdvisoryOrderField",
    "SecurityAdvisoryIdentifierFilter": "SecurityAdvisoryIdentifierFilter",
    "SecurityAdvisoryIdentifierType": "SecurityAdvisoryIdentifierType",
    "SecurityAdvisoryConnection": "SecurityAdvisoryConnection",
    "SecurityAdvisoryEdge": "SecurityAdvisoryEdge",
    "SecurityAdvisory": "SecurityAdvisory",
    "SecurityAdvisoryIdentifier": "SecurityAdvisoryIdentifier",
    "SecurityAdvisoryReference": "SecurityAdvisoryReference",
    "SecurityAdvisorySeverity": "SecurityAdvisorySeverity",
    "SecurityVulnerabilityOrder": "SecurityVulnerabilityOrder",
    "SecurityVulnerabilityOrderField": "SecurityVulnerabilityOrderField",
    "SecurityAdvisoryEcosystem": "SecurityAdvisoryEcosystem",
    "SecurityVulnerabilityConnection": "SecurityVulnerabilityConnection",
    "SecurityVulnerabilityEdge": "SecurityVulnerabilityEdge",
    "SecurityVulnerability": "SecurityVulnerability",
    "SecurityAdvisoryPackageVersion": "SecurityAdvisoryPackageVersion",
    "SecurityAdvisoryPackage": "SecurityAdvisoryPackage",
    "Mutation": "Mutation",
    "AcceptTopicSuggestionInput": "AcceptTopicSuggestionInput",
    "AcceptTopicSuggestionPayload": "AcceptTopicSuggestionPayload",
    "AddCommentInput": "AddCommentInput",
    "AddCommentPayload": "AddCommentPayload",
    "AddProjectCardInput": "AddProjectCardInput",
    "AddProjectCardPayload": "AddProjectCardPayload",
    "AddProjectColumnInput": "AddProjectColumnInput",
    "AddProjectColumnPayload": "AddProjectColumnPayload",
    "AddPullRequestReviewInput": "AddPullRequestReviewInput",
    "PullRequestReviewEvent": "PullRequestReviewEvent",
    "DraftPullRequestReviewComment": "DraftPullRequestReviewComment",
    "AddPullRequestReviewPayload": "AddPullRequestReviewPayload",
    "AddPullRequestReviewCommentInput": "AddPullRequestReviewCommentInput",
    "AddPullRequestReviewCommentPayload": "AddPullRequestReviewCommentPayload",
    "AddReactionInput": "AddReactionInput",
    "AddReactionPayload": "AddReactionPayload",
    "AddStarInput": "AddStarInput",
    "AddStarPayload": "AddStarPayload",
    "ChangeUserStatusInput": "ChangeUserStatusInput",
    "ChangeUserStatusPayload": "ChangeUserStatusPayload",
    "ClosePullRequestInput": "ClosePullRequestInput",
    "ClosePullRequestPayload": "ClosePullRequestPayload",
    "CreateBranchProtectionRuleInput": "CreateBranchProtectionRuleInput",
    "CreateBranchProtectionRulePayload": "CreateBranchProtectionRulePayload",
    "CreateProjectInput": "CreateProjectInput",
    "CreateProjectPayload": "CreateProjectPayload",
    "CreatePullRequestInput": "CreatePullRequestInput",
    "CreatePullRequestPayload": "CreatePullRequestPayload",
    "DeclineTopicSuggestionInput": "DeclineTopicSuggestionInput",
    "TopicSuggestionDeclineReason": "TopicSuggestionDeclineReason",
    "DeclineTopicSuggestionPayload": "DeclineTopicSuggestionPayload",
    "DeleteBranchProtectionRuleInput": "DeleteBranchProtectionRuleInput",
    "DeleteBranchProtectionRulePayload": "DeleteBranchProtectionRulePayload",
    "DeleteProjectInput": "DeleteProjectInput",
    "DeleteProjectPayload": "DeleteProjectPayload",
    "DeleteProjectCardInput": "DeleteProjectCardInput",
    "DeleteProjectCardPayload": "DeleteProjectCardPayload",
    "DeleteProjectColumnInput": "DeleteProjectColumnInput",
    "DeleteProjectColumnPayload": "DeleteProjectColumnPayload",
    "DeletePullRequestReviewInput": "DeletePullRequestReviewInput",
    "DeletePullRequestReviewPayload": "DeletePullRequestReviewPayload",
    "DeletePullRequestReviewCommentInput": "DeletePullRequestReviewCommentInput",
    "DeletePullRequestReviewCommentPayload": "DeletePullRequestReviewCommentPayload",
    "DismissPullRequestReviewInput": "DismissPullRequestReviewInput",
    "DismissPullRequestReviewPayload": "DismissPullRequestReviewPayload",
    "LockLockableInput": "LockLockableInput",
    "LockLockablePayload": "LockLockablePayload",
    "MergePullRequestInput": "MergePullRequestInput",
    "MergePullRequestPayload": "MergePullRequestPayload",
    "MoveProjectCardInput": "MoveProjectCardInput",
    "MoveProjectCardPayload": "MoveProjectCardPayload",
    "MoveProjectColumnInput": "MoveProjectColumnInput",
    "MoveProjectColumnPayload": "MoveProjectColumnPayload",
    "RemoveOutsideCollaboratorInput": "RemoveOutsideCollaboratorInput",
    "RemoveOutsideCollaboratorPayload": "RemoveOutsideCollaboratorPayload",
    "RemoveReactionInput": "RemoveReactionInput",
    "RemoveReactionPayload": "RemoveReactionPayload",
    "RemoveStarInput": "RemoveStarInput",
    "RemoveStarPayload": "RemoveStarPayload",
    "ReopenPullRequestInput": "ReopenPullRequestInput",
    "ReopenPullRequestPayload": "ReopenPullRequestPayload",
    "RequestReviewsInput": "RequestReviewsInput",
    "RequestReviewsPayload": "RequestReviewsPayload",
    "ResolveReviewThreadInput": "ResolveReviewThreadInput",
    "ResolveReviewThreadPayload": "ResolveReviewThreadPayload",
    "SubmitPullRequestReviewInput": "SubmitPullRequestReviewInput",
    "SubmitPullRequestReviewPayload": "SubmitPullRequestReviewPayload",
    "UnlockLockableInput": "UnlockLockableInput",
    "UnlockLockablePayload": "UnlockLockablePayload",
    "UnresolveReviewThreadInput": "UnresolveReviewThreadInput",
    "UnresolveReviewThreadPayload": "UnresolveReviewThreadPayload",
    "UpdateBranchProtectionRuleInput": "UpdateBranchProtectionRuleInput",
    "UpdateBranchProtectionRulePayload": "UpdateBranchProtectionRulePayload",
    "UpdateProjectInput": "UpdateProjectInput",
    "UpdateProjectPayload": "UpdateProjectPayload",
    "UpdateProjectCardInput": "UpdateProjectCardInput",
    "UpdateProjectCardPayload": "UpdateProjectCardPayload",
    "UpdateProjectColumnInput": "UpdateProjectColumnInput",
    "UpdateProjectColumnPayload": "UpdateProjectColumnPayload",
    "UpdatePullRequestInput": "UpdatePullRequestInput",
    "UpdatePullRequestPayload": "UpdatePullRequestPayload",
    "UpdatePullRequestReviewInput": "UpdatePullRequestReviewInput",
    "UpdatePullRequestReviewPayload": "UpdatePullRequestReviewPayload",
    "UpdatePullRequestReviewCommentInput": "UpdatePullRequestReviewCommentInput",
    "UpdatePullRequestReviewCommentPayload": "UpdatePullRequestReviewCommentPayload",
    "UpdateSubscriptionInput": "UpdateSubscriptionInput",
    "UpdateSubscriptionPayload": "UpdateSubscriptionPayload",
    "UpdateTopicsInput": "UpdateTopicsInput",
    "UpdateTopicsPayload": "UpdateTopicsPayload",
    "__Schema": "__Schema",
    "__Type": "__Type",
    "__TypeKind": "__TypeKind",
    "__Field": "__Field",
    "__InputValue": "__InputValue",
    "__EnumValue": "__EnumValue",
    "__Directive": "__Directive",
    "__DirectiveLocation": "__DirectiveLocation",
    "Float": "Float",
    "DefaultRepositoryPermissionField": "DefaultRepositoryPermissionField",
    "RepositoryInvitationEdge": "RepositoryInvitationEdge",
    "RepositoryInvitation": "RepositoryInvitation",
    "IdentityProviderConfigurationState": "IdentityProviderConfigurationState",
    "Bot": "Bot",
    "Blob": "Blob",
    "PullRequestOrder": "PullRequestOrder",
    "PullRequestOrderField": "PullRequestOrderField",
    "IssuePubSubTopic": "IssuePubSubTopic",
    "PullRequestPubSubTopic": "PullRequestPubSubTopic",
    "PullRequestTimelineItemsEdge": "PullRequestTimelineItemsEdge",
    "PullRequestTimelineItems": "PullRequestTimelineItems",
    "BaseRefChangedEvent": "BaseRefChangedEvent",
    "AddedToProjectEvent": "AddedToProjectEvent",
    "CommentDeletedEvent": "CommentDeletedEvent",
    "ConvertedNoteToIssueEvent": "ConvertedNoteToIssueEvent",
    "MentionedEvent": "MentionedEvent",
    "MovedColumnsInProjectEvent": "MovedColumnsInProjectEvent",
    "PinnedEvent": "PinnedEvent",
    "RemovedFromProjectEvent": "RemovedFromProjectEvent",
    "UnpinnedEvent": "UnpinnedEvent",
    "PullRequestTimelineItemsItemType": "PullRequestTimelineItemsItemType",
    "IssueTimelineItemsEdge": "IssueTimelineItemsEdge",
    "IssueTimelineItems": "IssueTimelineItems",
    "IssueTimelineItemsItemType": "IssueTimelineItemsItemType",
    "RepositoryCollaboratorAffiliation": "RepositoryCollaboratorAffiliation",
    "TopicConnection": "TopicConnection",
    "TopicEdge": "TopicEdge",
    "CreatedRepositoryContributionEdge": "CreatedRepositoryContributionEdge",
    "AppEdge": "AppEdge",
    "CollectionItemContent": "CollectionItemContent",
    "MinimizeCommentInput": "MinimizeCommentInput",
    "ReportedContentClassifiers": "ReportedContentClassifiers",
    "UnminimizeCommentInput": "UnminimizeCommentInput",
    "ImportProjectInput": "ImportProjectInput",
    "ProjectColumnImport": "ProjectColumnImport",
    "ProjectCardImport": "ProjectCardImport",
    "DeleteIssueInput": "DeleteIssueInput",
    "PinIssueInput": "PinIssueInput",
    "UnpinIssueInput": "UnpinIssueInput",
    "UpdateBusinessProfileInput": "UpdateBusinessProfileInput",
    "InviteBusinessAdminInput": "InviteBusinessAdminInput",
    "AcceptBusinessMemberInvitationInput": "AcceptBusinessMemberInvitationInput",
    "CancelBusinessAdminInvitationInput": "CancelBusinessAdminInvitationInput",
    "RemoveBusinessAdminInput": "RemoveBusinessAdminInput",
    "InviteBusinessBillingManagerInput": "InviteBusinessBillingManagerInput",
    "CancelBusinessBillingManagerInvitationInput": "CancelBusinessBillingManagerInvitationInput",
    "RemoveBusinessBillingManagerInput": "RemoveBusinessBillingManagerInput",
    "SetBusinessIdentityProviderInput": "SetBusinessIdentityProviderInput",
    "RemoveBusinessIdentityProviderInput": "RemoveBusinessIdentityProviderInput",
    "RegenerateBusinessIdentityProviderRecoveryCodesInput": "RegenerateBusinessIdentityProviderRecoveryCodesInput",
    "UpdateBusinessMembersCanCreateRepositoriesSettingInput": "UpdateBusinessMembersCanCreateRepositoriesSettingInput",
    "UpdateBusinessAllowPrivateRepositoryForkingSettingInput": "UpdateBusinessAllowPrivateRepositoryForkingSettingInput",
    "UpdateBusinessDefaultRepositoryPermissionSettingInput": "UpdateBusinessDefaultRepositoryPermissionSettingInput",
    "UpdateBusinessTeamDiscussionsSettingInput": "UpdateBusinessTeamDiscussionsSettingInput",
    "UpdateBusinessOrganizationProjectsSettingInput": "UpdateBusinessOrganizationProjectsSettingInput",
    "UpdateBusinessRepositoryProjectsSettingInput": "UpdateBusinessRepositoryProjectsSettingInput",
    "UpdateBusinessMembersCanChangeRepositoryVisibilitySettingInput": "UpdateBusinessMembersCanChangeRepositoryVisibilitySettingInput",
    "UpdateBusinessMembersCanInviteCollaboratorsSettingInput": "UpdateBusinessMembersCanInviteCollaboratorsSettingInput",
    "UpdateBusinessMembersCanDeleteRepositoriesSettingInput": "UpdateBusinessMembersCanDeleteRepositoriesSettingInput",
    "UpdateBusinessTwoFactorAuthenticationRequiredSettingInput": "UpdateBusinessTwoFactorAuthenticationRequiredSettingInput",
    "UpdateBusinessMembersCanUpdateProtectedBranchesSettingInput": "UpdateBusinessMembersCanUpdateProtectedBranchesSettingInput",
    "UpdateBusinessMembersCanDeleteIssuesSettingInput": "UpdateBusinessMembersCanDeleteIssuesSettingInput",
    "ContentAttachment": "ContentAttachment",
    "ContentReference": "ContentReference",
    "CreateContentAttachmentInput": "CreateContentAttachmentInput",
    "GpgSignature": "GpgSignature",
    "SmimeSignature": "SmimeSignature",
    "Tag": "Tag",
    "UnknownSignature": "UnknownSignature"
  },
  "_possibleTypeMap": {},
  "_implementations": {
    "Node": [
      "CodeOfConduct",
      "License",
      "MarketplaceCategory",
      "MarketplaceListing",
      "App",
      "Organization",
      "Project",
      "ProjectColumn",
      "ProjectCard",
      "Issue",
      "User",
      "Repository",
      "BranchProtectionRule",
      "Ref",
      "PullRequest",
      "UserContentEdit",
      "Label",
      "Reaction",
      "IssueComment",
      "PullRequestCommit",
      "Commit",
      "CommitComment",
      "Deployment",
      "DeploymentStatus",
      "Status",
      "StatusContext",
      "Tree",
      "Milestone",
      "ReviewRequest",
      "Team",
      "UserStatus",
      "OrganizationInvitation",
      "PullRequestReviewThread",
      "PullRequestReviewComment",
      "PullRequestReview",
      "CommitCommentThread",
      "ClosedEvent",
      "ReopenedEvent",
      "SubscribedEvent",
      "UnsubscribedEvent",
      "MergedEvent",
      "ReferencedEvent",
      "CrossReferencedEvent",
      "AssignedEvent",
      "UnassignedEvent",
      "LabeledEvent",
      "UnlabeledEvent",
      "MilestonedEvent",
      "DemilestonedEvent",
      "RenamedTitleEvent",
      "LockedEvent",
      "UnlockedEvent",
      "DeployedEvent",
      "DeploymentEnvironmentChangedEvent",
      "HeadRefDeletedEvent",
      "HeadRefRestoredEvent",
      "HeadRefForcePushedEvent",
      "BaseRefForcePushedEvent",
      "ReviewRequestedEvent",
      "ReviewRequestRemovedEvent",
      "ReviewDismissedEvent",
      "PushAllowance",
      "ReviewDismissalAllowance",
      "DeployKey",
      "Language",
      "ProtectedBranch",
      "Release",
      "ReleaseAsset",
      "RepositoryTopic",
      "Topic",
      "Gist",
      "GistComment",
      "PublicKey",
      "TransferredEvent",
      "OrganizationIdentityProvider",
      "ExternalIdentity",
      "SecurityAdvisory",
      "RepositoryInvitation",
      "Bot",
      "Blob",
      "BaseRefChangedEvent",
      "AddedToProjectEvent",
      "CommentDeletedEvent",
      "ConvertedNoteToIssueEvent",
      "MentionedEvent",
      "MovedColumnsInProjectEvent",
      "PinnedEvent",
      "RemovedFromProjectEvent",
      "UnpinnedEvent",
      "Tag"
    ],
    "Actor": [
      "Organization",
      "User",
      "Bot"
    ],
    "RegistryPackageOwner": [
      "Organization",
      "User",
      "Repository"
    ],
    "RegistryPackageSearch": [
      "Organization",
      "User"
    ],
    "ProjectOwner": [
      "Organization",
      "User",
      "Repository"
    ],
    "RepositoryOwner": [
      "Organization",
      "User"
    ],
    "UniformResourceLocatable": [
      "Organization",
      "Issue",
      "User",
      "Repository",
      "PullRequest",
      "PullRequestCommit",
      "Commit",
      "Milestone",
      "ClosedEvent",
      "MergedEvent",
      "CrossReferencedEvent",
      "ReviewDismissedEvent",
      "Release",
      "RepositoryTopic",
      "Bot"
    ],
    "MemberStatusable": [
      "Organization",
      "Team"
    ],
    "Closable": [
      "Project",
      "Issue",
      "PullRequest",
      "Milestone"
    ],
    "Updatable": [
      "Project",
      "Issue",
      "PullRequest",
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview",
      "GistComment"
    ],
    "ProjectCardItem": [],
    "Assignable": [
      "Issue",
      "PullRequest"
    ],
    "Comment": [
      "Issue",
      "PullRequest",
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview",
      "GistComment"
    ],
    "UpdatableComment": [
      "Issue",
      "PullRequest",
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview",
      "GistComment"
    ],
    "Labelable": [
      "Issue",
      "PullRequest"
    ],
    "Lockable": [
      "Issue",
      "PullRequest"
    ],
    "Reactable": [
      "Issue",
      "PullRequest",
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview"
    ],
    "RepositoryNode": [
      "Issue",
      "PullRequest",
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview",
      "CommitCommentThread"
    ],
    "Subscribable": [
      "Issue",
      "Repository",
      "PullRequest",
      "Commit",
      "Team"
    ],
    "Starrable": [
      "Repository",
      "Topic",
      "Gist"
    ],
    "RepositoryInfo": [
      "Repository"
    ],
    "Deletable": [
      "IssueComment",
      "CommitComment",
      "PullRequestReviewComment",
      "PullRequestReview",
      "GistComment"
    ],
    "GitObject": [
      "Commit",
      "Tree",
      "Blob",
      "Tag"
    ],
    "GitSignature": [
      "GpgSignature",
      "SmimeSignature",
      "UnknownSignature"
    ],
    "RequestedReviewer": [],
    "PullRequestTimelineItem": [],
    "Closer": [],
    "ReferencedSubject": [],
    "MilestoneItem": [],
    "RenamedTitleSubject": [],
    "PushAllowanceActor": [],
    "ReviewDismissalAllowanceActor": [],
    "IssueOrPullRequest": [],
    "Contribution": [
      "CreatedCommitContribution",
      "CreatedIssueContribution",
      "RestrictedContribution",
      "CreatedPullRequestContribution",
      "CreatedRepositoryContribution",
      "JoinedGitHubContribution"
    ],
    "CreatedIssueOrRestrictedContribution": [],
    "CreatedPullRequestOrRestrictedContribution": [],
    "CreatedRepositoryOrRestrictedContribution": [],
    "IssueTimelineItem": [],
    "SearchResultItem": [],
    "PullRequestTimelineItems": [],
    "IssueTimelineItems": [],
    "CollectionItemContent": []
  }
}